spring:
  application:
    name: library-manager
  datasource:
    url: jdbc:postgresql://localhost:5432/library-manager
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true

google:
  books:
    api-key:
