spring:
  application:
    name: library-manager
  datasource:
    url: jdbc:postgresql://localhost:5432/library-manager
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        generate_statistics: true
        jdbc:
          lob:
            non_contextual_creation: true
