module.exports = {
  endOfLine: "crlf",
  arrowParens: "always",
  bracketSameLine: false,
  bracketSpacing: true,
  semi: true,
  singleQuote: true,
  jsxSingleQuote: true,
  quoteProps: "consistent",
  trailingComma: "all",
  singleAttributePerLine: true,
  htmlWhitespaceSensitivity: "css",
  vueIndentScriptAndStyle: false,
  proseWrap: "preserve",
  insertPragma: false,
  printWidth: 120,
  requirePragma: false,
  tabWidth: 2,
  useTabs: false,
  embeddedLanguageFormatting: "auto",
};
